### ISSUE TITLE
Fails to load; gedit 44.2; Manjaro 22.1.0

### ISSUE THREAD

**Issue by sevaseva** [maoschanz/gedit-plugin-markdown_preview#52]
Cloned revision cc711c00a4ed11b89b2ecc604e4a7aa9c163adb7
Ran ./install.sh as a non-root
Enabled the plugin in gedit
Closed all gedit instances
Started it again (not sure if any of the printed WARNINGs are relevant):

```bash
$ gedit foo.md

** (gedit:43458): WARNING **: 23:00:54.120: Error initializing Python Plugin Loader: PyGObject initialization failed
ImportError: could not import gobject (error was: ModuleNotFoundError("No module named 'gi'"))

** (gedit:43458): WARNING **: 23:00:54.120: Please check the installation of all the Python related packages required by libpeas and try again

(gedit:43458): libpeas-WARNING **: 23:00:54.120: Loader 'python3' is not a valid PeasPluginLoader instance

** (gedit:43458): WARNING **: 23:00:54.216: Error loading plugin: libaspell.so.15: cannot open shared object file: No such file or directory


** (gedit:43458): WARNING **: 23:00:54.216: Error loading plugin: libhspell.so.0: cannot open shared object file: No such file or directory


** (gedit:43458): WARNING **: 23:00:54.216: Error loading plugin: libnuspell.so.5: cannot open shared object file: No such file or directory


** (gedit:43458): WARNING **: 23:00:54.216: Error loading plugin: libvoikko.so.1: cannot open shared object file: No such file or directory


** (gedit:43458): WARNING **: 23:00:54.216: Error loading plugin: libaspell.so.15: cannot open shared object file: No such file or directory


** (gedit:43458): WARNING **: 23:00:54.216: Error loading plugin: libhspell.so.0: cannot open shared object file: No such file or directory


** (gedit:43458): WARNING **: 23:00:54.216: Error loading plugin: libnuspell.so.5: cannot open shared object file: No such file or directory


** (gedit:43458): WARNING **: 23:00:54.216: Error loading plugin: libvoikko.so.1: cannot open shared object file: No such file or directory

```

![image](https://user-images.githubusercontent.com/1168195/234773629-e603c60f-6e50-44f8-819b-392b65a90cb0.png)

Let me know if I can help debug, e.g. give you more information about the system or try a fix, etc.

Thanks!

**Comment by sevaseva** [comment]
On the same system, with nothing changed, when starting gedit using gnome app launcher (i.e. "the normal way", not from the command line) the plugin loads fine, but renders no Markdown:

![image](https://user-images.githubusercontent.com/1168195/234776960-7c56851c-397d-4da7-9be6-a7abbe7a0650.png)

**Comment by FerdiScholten** [comment]
Same issue on Ubuntu 23.04 with gedit 44.2
The plugin loads in gedit and can be configured but does not render any output (blank window) when starting gedit in a terminal I get this:

```
Traceback (most recent call last):
  File "/home/ferdi/.local/share/gedit/plugins/markdown_preview/main_container.py", line 356, in on_file_changed
    self.file_format = self.recognize_format()
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ferdi/.local/share/gedit/plugins/markdown_preview/main_container.py", line 364, in recognize_format
    name = doc.get_short_name_for_display()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Document' object has no attribute 'get_short_name_for_display'
```

**Comment by FerdiScholten** [comment]
So above is indeed the root cause why this plugin no longer works in gedit 44.2, found this on https://gitlab.gnome.org/GNOME/gedit/-/blob/master/docs/reference/api-breaks.xml

The gedit_document_get_short_name_for_display() function has been
          removed, use
          tepl_file_get_short_name()
          instead.

**Comment by maoschanz** [comment]
Your issues are different ones

@sevaseva i believe you're missing python3-gi, which on manjaro is probably named `python-gobject`. If it is already installed, then it's a problem of how python is set up: i forgot how it worked though. A quick google search tells me it's a common issue among Arch-based distros users

@FerdiScholten the stable version isn't compatible with gedit 44 yet, the issue you were looking for is #48. You can either use the unstable "master" branch like @sevaseva did (i don't recommend it because it's full of unfinished buggy code), or you can wait a few days until i test and publish a proper release

**Comment by dtrunk90** [comment]
Can we expect a proper release soon?

**Comment by maoschanz** [comment]
> Can we expect a proper release soon?

done! i hope it works...

**Comment by dtrunk90** [comment]
Yes, it does. Thank you!
